export const arrangements = [
  {
    id: "DdVCa_EGsqb-1",
    name: "Last week’s deliveries",
    category: "Celebrations",
    image: "/images/gallery/DdVCa_EGsqb-1.jpg",
    tag: "From the studio",
    description: "Some of the arrangements that went out last week — soft seasonal blooms gathered with care.",
  },
  {
    id: "DdVCa_EGsqb-2",
    name: "Last week’s deliveries · 2",
    category: "Celebrations",
    image: "/images/gallery/DdVCa_EGsqb-2.jpg",
    tag: "From the studio",
    description: "Some of the arrangements that went out last week — soft seasonal blooms gathered with care.",
  },
  {
    id: "DdVCa_EGsqb-3",
    name: "Last week’s deliveries · 3",
    category: "Celebrations",
    image: "/images/gallery/DdVCa_EGsqb-3.jpg",
    tag: "From the studio",
    description: "Some of the arrangements that went out last week — soft seasonal blooms gathered with care.",
  },
  {
    id: "DdVCa_EGsqb-4",
    name: "Last week’s deliveries · 4",
    category: "Celebrations",
    image: "/images/gallery/DdVCa_EGsqb-4.jpg",
    tag: "From the studio",
    description: "Some of the arrangements that went out last week — soft seasonal blooms gathered with care.",
  },
  {
    id: "DdVCa_EGsqb-5",
    name: "Last week’s deliveries · 5",
    category: "Celebrations",
    image: "/images/gallery/DdVCa_EGsqb-5.jpg",
    tag: "From the studio",
    description: "Some of the arrangements that went out last week — soft seasonal blooms gathered with care.",
  },
  {
    id: "DdP2FViGm4G-1",
    name: "Monochromatic blush",
    category: "Celebrations",
    image: "/images/gallery/DdP2FViGm4G-1.jpg",
    tag: "A little celebration",
    description: "Monochromatic tones in blush and coral — romantic, modern, and full of heart.",
  },
  {
    id: "DdP2FViGm4G-2",
    name: "Monochromatic blush · 2",
    category: "Celebrations",
    image: "/images/gallery/DdP2FViGm4G-2.jpg",
    tag: "A little celebration",
    description: "Monochromatic tones in blush and coral — romantic, modern, and full of heart.",
  },
  {
    id: "DdP2FViGm4G-3",
    name: "Monochromatic blush · 3",
    category: "Celebrations",
    image: "/images/gallery/DdP2FViGm4G-3.jpg",
    tag: "A little celebration",
    description: "Monochromatic tones in blush and coral — romantic, modern, and full of heart.",
  },
  {
    id: "DdP2FViGm4G-4",
    name: "Monochromatic blush · 4",
    category: "Celebrations",
    image: "/images/gallery/DdP2FViGm4G-4.jpg",
    tag: "A little celebration",
    description: "Monochromatic tones in blush and coral — romantic, modern, and full of heart.",
  },
  {
    id: "DdM1DSWmngR-1",
    name: "Favorite flowers",
    category: "Celebrations",
    image: "/images/gallery/DdM1DSWmngR-1.jpg",
    tag: "Seasonal favorite",
    description: "A mix of our favorite flowers — loose, joyful, and always changing with the season.",
  },
  {
    id: "DdM1DSWmngR-2",
    name: "Favorite flowers · 2",
    category: "Celebrations",
    image: "/images/gallery/DdM1DSWmngR-2.jpg",
    tag: "Seasonal favorite",
    description: "A mix of our favorite flowers — loose, joyful, and always changing with the season.",
  },
  {
    id: "DdM1DSWmngR-3",
    name: "Favorite flowers · 3",
    category: "Celebrations",
    image: "/images/gallery/DdM1DSWmngR-3.jpg",
    tag: "Seasonal favorite",
    description: "A mix of our favorite flowers — loose, joyful, and always changing with the season.",
  },
  {
    id: "DdM1DSWmngR-4",
    name: "Favorite flowers · 4",
    category: "Celebrations",
    image: "/images/gallery/DdM1DSWmngR-4.jpg",
    tag: "Seasonal favorite",
    description: "A mix of our favorite flowers — loose, joyful, and always changing with the season.",
  },
  {
    id: "DdIPmxnHKga-1",
    name: "Textures & garden roses",
    category: "Celebrations",
    image: "/images/gallery/DdIPmxnHKga-1.jpg",
    tag: "Bestseller",
    description: "Rich textures with garden roses for a soft, feminine touch — one of our most-loved styles.",
  },
  {
    id: "DdIPmxnHKga-2",
    name: "Textures & garden roses · 2",
    category: "Celebrations",
    image: "/images/gallery/DdIPmxnHKga-2.jpg",
    tag: "Bestseller",
    description: "Rich textures with garden roses for a soft, feminine touch — one of our most-loved styles.",
  },
  {
    id: "DdIPmxnHKga-3",
    name: "Textures & garden roses · 3",
    category: "Celebrations",
    image: "/images/gallery/DdIPmxnHKga-3.jpg",
    tag: "Bestseller",
    description: "Rich textures with garden roses for a soft, feminine touch — one of our most-loved styles.",
  },
  {
    id: "DdIPmxnHKga-4",
    name: "Textures & garden roses · 4",
    category: "Celebrations",
    image: "/images/gallery/DdIPmxnHKga-4.jpg",
    tag: "Bestseller",
    description: "Rich textures with garden roses for a soft, feminine touch — one of our most-loved styles.",
  },
  {
    id: "DcxJ2G5HOPD-1",
    name: "August arrangements",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-1.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-2",
    name: "August arrangements · 2",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-2.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-3",
    name: "August arrangements · 3",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-3.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-4",
    name: "August arrangements · 4",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-4.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-5",
    name: "August arrangements · 5",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-5.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-6",
    name: "August arrangements · 6",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-6.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-7",
    name: "August arrangements · 7",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-7.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-8",
    name: "August arrangements · 8",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-8.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-9",
    name: "August arrangements · 9",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-9.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-10",
    name: "August arrangements · 10",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-10.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-11",
    name: "August arrangements · 11",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-11.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-12",
    name: "August arrangements · 12",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-12.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-13",
    name: "August arrangements · 13",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-13.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-14",
    name: "August arrangements · 14",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-14.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-15",
    name: "August arrangements · 15",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-15.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcxJ2G5HOPD-16",
    name: "August arrangements · 16",
    category: "Celebrations",
    image: "/images/gallery/DcxJ2G5HOPD-16.jpg",
    tag: "From the studio",
    description: "A signature Studio Sol arrangement — sculptural, seasonal, and made with love.",
  },
  {
    id: "DcudfgBHJRR-1",
    name: "Delivery day",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-1.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "DcudfgBHJRR-2",
    name: "Delivery day · 2",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-2.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "DcudfgBHJRR-3",
    name: "Delivery day · 3",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-3.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "DcudfgBHJRR-4",
    name: "Delivery day · 4",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-4.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "DcudfgBHJRR-5",
    name: "Delivery day · 5",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-5.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "DcudfgBHJRR-6",
    name: "Delivery day · 6",
    category: "Celebrations",
    image: "/images/gallery/DcudfgBHJRR-6.jpg",
    tag: "Local delivery",
    description: "Fresh deliveries heading out across Austin — flowers for everyday moments.",
  },
  {
    id: "Dcj7zIjGsJd",
    name: "Monochromatic green",
    category: "Corporate",
    image: "/images/gallery/Dcj7zIjGsJd.jpg",
    tag: "Seasonal favorite",
    description: "A monochromatic arrangement in fresh greens — clean, graphic, and unexpected.",
  },
  {
    id: "DcPQZotGsfm-1",
    name: "Soft seasonal mix",
    category: "Celebrations",
    image: "/images/gallery/DcPQZotGsfm-1.jpg",
    tag: "From the studio",
    description: "A soft seasonal mix — thoughtful stems arranged for someone special.",
  },
  {
    id: "DcPQZotGsfm-2",
    name: "Soft seasonal mix · 2",
    category: "Celebrations",
    image: "/images/gallery/DcPQZotGsfm-2.jpg",
    tag: "From the studio",
    description: "A soft seasonal mix — thoughtful stems arranged for someone special.",
  },
  {
    id: "DcPQZotGsfm-3",
    name: "Soft seasonal mix · 3",
    category: "Celebrations",
    image: "/images/gallery/DcPQZotGsfm-3.jpg",
    tag: "From the studio",
    description: "A soft seasonal mix — thoughtful stems arranged for someone special.",
  },
  {
    id: "DcNFA_NnMel-1",
    name: "Sculptural & masculine",
    category: "Corporate",
    image: "/images/gallery/DcNFA_NnMel-1.jpg",
    tag: "Statement piece",
    description: "Sculptural and masculine — bold shapes and rich texture for a striking centerpiece.",
  },
  {
    id: "DcNFA_NnMel-2",
    name: "Sculptural & masculine · 2",
    category: "Corporate",
    image: "/images/gallery/DcNFA_NnMel-2.jpg",
    tag: "Statement piece",
    description: "Sculptural and masculine — bold shapes and rich texture for a striking centerpiece.",
  },
  {
    id: "DcNFA_NnMel-3",
    name: "Sculptural & masculine · 3",
    category: "Corporate",
    image: "/images/gallery/DcNFA_NnMel-3.jpg",
    tag: "Statement piece",
    description: "Sculptural and masculine — bold shapes and rich texture for a striking centerpiece.",
  },
  {
    id: "DcNFA_NnMel-4",
    name: "Sculptural & masculine · 4",
    category: "Corporate",
    image: "/images/gallery/DcNFA_NnMel-4.jpg",
    tag: "Statement piece",
    description: "Sculptural and masculine — bold shapes and rich texture for a striking centerpiece.",
  },
  {
    id: "Dbt69XjGmRH-1",
    name: "Same, but different",
    category: "Celebrations",
    image: "/images/gallery/Dbt69XjGmRH-1.jpg",
    tag: "Designer’s choice",
    description: "Two takes on the same palette — proof that every arrangement has its own personality.",
  },
  {
    id: "Dbt69XjGmRH-2",
    name: "Same, but different · 2",
    category: "Celebrations",
    image: "/images/gallery/Dbt69XjGmRH-2.jpg",
    tag: "Designer’s choice",
    description: "Two takes on the same palette — proof that every arrangement has its own personality.",
  },
  {
    id: "Dbt69XjGmRH-3",
    name: "Same, but different · 3",
    category: "Celebrations",
    image: "/images/gallery/Dbt69XjGmRH-3.jpg",
    tag: "Designer’s choice",
    description: "Two takes on the same palette — proof that every arrangement has its own personality.",
  },
  {
    id: "Dbt69XjGmRH-4",
    name: "Same, but different · 4",
    category: "Celebrations",
    image: "/images/gallery/Dbt69XjGmRH-4.jpg",
    tag: "Designer’s choice",
    description: "Two takes on the same palette — proof that every arrangement has its own personality.",
  },
  {
    id: "Dbo-6LXHMxT-1",
    name: "Today’s delivery",
    category: "Celebrations",
    image: "/images/gallery/Dbo-6LXHMxT-1.jpg",
    tag: "From the studio",
    description: "Today’s delivery and a few other things we love — fresh from the studio bench.",
  },
  {
    id: "Dbo-6LXHMxT-2",
    name: "Today’s delivery · 2",
    category: "Celebrations",
    image: "/images/gallery/Dbo-6LXHMxT-2.jpg",
    tag: "From the studio",
    description: "Today’s delivery and a few other things we love — fresh from the studio bench.",
  },
];

export const stories = [
  {
    slug: 'make-your-flowers-last',
    title: 'A little care, a little longer.',
    category: 'FLOWER CARE',
    image: "/images/gallery/DdIPmxnHKga-1.jpg",
    intro: 'Simple rituals to keep your flowers happy, day after day.',
    body: [
      'Start with a clean vase and fresh, room-temperature water. Remove any leaves that will sit below the waterline.',
      'Trim the stems at an angle with clean, sharp scissors, then place them in water straight away. Use the flower food supplied with your arrangement according to its instructions.',
      'Keep your flowers away from direct sunlight, heating vents, and ripening fruit. Refresh the water every two days and give the stems another small trim.',
      'Remove faded flowers as you go. Every stem has its own rhythm, and a little attention makes the whole arrangement last longer.',
    ],
  },
  {
    slug: 'the-beauty-of-seasonal-flowers',
    title: 'Let the season choose.',
    category: 'FROM THE STUDIO',
    image: "/images/gallery/DdM1DSWmngR-1.jpg",
    intro: 'Why our favorite arrangements begin with what’s growing now.',
    body: [
      'Seasonal flowers bring a sense of place and time to an arrangement. They remind us to notice what is happening just outside our door.',
      'In spring, we love the movement of tulips and ranunculus. Summer brings abundant garden roses and dahlias, while autumn invites richer colors and textural foliage.',
      'A designer’s choice bouquet is an invitation to work with the most beautiful stems available that week. Your flowers may look a little different each time—that is part of their charm.',
    ],
  },
];
